### ISSUE TITLE
videojs.obj.merge

### ISSUE THREAD

**Issue by campones** [TylerZubke/Videojs-AFK-Monitor#8]
Hello
I m trying videojs 8 and I get a warning that videojs.mergeOptions is deprecated  (and will be removed from vjs 9) so I changed for the videojs.obj.merge as they say but then the plugin doesn't work anymore

**Comment by TylerZubke** [comment]
I just updated it. Should work with videojs 9 now.

**Comment by campones** [comment]
> I just updated it. Should work with videojs 9 now.

I had done those changes and wasn't working after, just the    ` videojs.registerPlugin('AFKMonitor', AFKMonitor); `  does
